C----------------------------------------------------------
      FUNCTION EEWIWJ(Z)
      IMPLICIT NONE
      COMMON/BSQRK/ RS,M1,M2,AE,BE,PROPZ,E4,MZ
      COMMON/EPOL/ FLEM,FREP,FREM,FLEP
      COMMON/STUFF/ UNITS,PI
      COMMON/N1N1/ G,COSGR,SINGR,MWI
      COMMON/WIWJ/ X,Y,MSN,THY,GRTERM,CS2THW
      REAL Z,SSXLAM,EEWIWJ
      REAL RS,M1,M2,AE,BE,PROPZ,E4,MZ,G,COSGR,SINGR,MWI(2)
      REAL FLEM,FREP,FREM,FLEP,UNITS,PI
      REAL S,P,E,SIGLR,SIGRL
      REAL X,Y,MSN,THY,GRTERM,CS2THW,CT2THW,SN2THW,COTW,TANW
      REAL MZZR,MZZL,MNNL,MZNL,MW1,MW2,XI,DEL
      CT2THW=CS2THW/(1.-CS2THW)
      SN2THW=1.-CS2THW
      COTW=SQRT(CT2THW)
      TANW=1./COTW
      MW1=ABS(MWI(1))
      MW2=ABS(MWI(2))
      S=RS**2
      P=SQRT(SSXLAM(S,M1**2,M2**2))/2./RS
      E=RS/2.
      XI=-SIGN(1.,MWI(1))*SIGN(1.,MWI(2))
      DEL=(MW2**2-MW1**2)/4./E
      MZZR=4*(AE+BE)**2*(COTW+TANW)**2/PROPZ*
     ,((X**2+Y**2)*(E**2+P**2*Z**2-DEL**2-XI*MW1*MW2)+
     ,2*X**2*XI*MW1*MW2-4*X*Y*E*P*Z)
      MZZL=4*(AE-BE)**2*(COTW+TANW)**2/PROPZ*
     ,((X**2+Y**2)*(E**2+P**2*Z**2-DEL**2-XI*MW1*MW2)+
     ,2*X**2*XI*MW1*MW2+4*X*Y*E*P*Z)
      MNNL=2*GRTERM**2*((E-P*Z)**2-DEL**2)/SN2THW**2/
     ,(2*E*(E-DEL)-2*E*P*Z+MSN**2-M1**2)**2
      MZNL=-4*THY*(AE-BE)*(COTW+TANW)*GRTERM*(S-MZ**2)/
     ,SN2THW/PROPZ*
     ,((X-Y)*((E-P*Z)**2-DEL**2-XI*MW1*MW2)+2*X*XI*MW1*MW2)/
     ,(2*E*(E-DEL)-2*E*P*Z+MSN**2-MW1**2)
      SIGRL=E4*P*MZZR/64./PI/E
      SIGLR=E4*P*(MZZL+MNNL+MZNL)/64./PI/E
      EEWIWJ=(FLEM*FREP*SIGLR+FREM*FLEP*SIGRL)*UNITS
      RETURN
      END
