C----------------------------------------------------------
      FUNCTION EEWIWI(Z)
      IMPLICIT NONE
      COMMON/BSQRK/ RS,M1,M2,AE,BE,PROPZ,E4,MZ
      COMMON/EPOL/ FLEM,FREP,FREM,FLEP
      COMMON/STUFF/ UNITS,PI
      COMMON/N1N1/ G,COSGR,SINGR,MWI
      COMMON/WIWJ/ X,Y,MSN,THY,GRTERM,CS2THW
      REAL Z,SSXLAM,EEWIWI
      REAL RS,M1,M2,AE,BE,PROPZ,E4,MZ,G,COSGR,SINGR,MWI(2)
      REAL FLEM,FREP,FREM,FLEP,UNITS,PI
      REAL S,P,E,SIGLR,SIGRL
      REAL X,Y,MSN,THY,GRTERM,CS2THW,CT2THW,SN2THW
      REAL MWIS,MGGR,MGGL,MZZR,MZZL,MGZR,MGZL,MNNL,MGNL,MZNL
      SN2THW=1.-CS2THW
      CT2THW=CS2THW/SN2THW
      S=RS**2
      P=SQRT(SSXLAM(S,M1**2,M2**2))/2./RS
      E=RS/2.
      MWIS=M1**2
      MGGR=16*E4*(E**2*(1.+Z**2)+MWIS*(1.-Z**2))/S
      MGGL=MGGR
      MZZR=16*E4*CT2THW*S*((X**2+Y**2)*(AE+BE)**2*
     ,(E**2*(1.+Z**2)+MWIS*(1.-Z**2))-2*Y**2*(AE+BE)**2*MWIS-
     ,4*X*Y*(AE+BE)**2*E*P*Z)/PROPZ
      MZZL=16*E4*CT2THW*S*((X**2+Y**2)*(AE-BE)**2*
     ,(E**2*(1.+Z**2)+MWIS*(1.-Z**2))-2*Y**2*(AE-BE)**2*MWIS+
     ,4*X*Y*(AE-BE)**2*E*P*Z)/PROPZ
      MGZR=-32*E4*(AE+BE)*SQRT(CT2THW)*(S-MZ**2)/PROPZ*
     ,(X*(E**2*(1.+Z**2)+MWIS*(1.-Z**2))-2*Y*E*P*Z)
      MGZL=-32*E4*(AE-BE)*SQRT(CT2THW)*(S-MZ**2)/PROPZ*
     ,(X*(E**2*(1.+Z**2)+MWIS*(1.-Z**2))+2*Y*E*P*Z)
      MNNL=2*E4*GRTERM**2*S*(E-P*Z)**2/SN2THW**2/
     ,(E**2+P**2-2*E*P*Z+MSN**2)**2
      MGNL=-8*E4*GRTERM*((E-P*Z)**2+MWIS)/SN2THW/
     ,(E**2+P**2-2*E*P*Z+MSN**2)
      MZNL=8*E4*(AE-BE)*SQRT(CT2THW)*GRTERM*S*(S-MZ**2)/SN2THW/PROPZ*
     ,((X-Y)*((E-P*Z)**2+MWIS)+2*Y*MWIS)/(E**2+P**2-2*E*P*Z+MSN**2)
      SIGRL=P*(MGGR+MZZR+MGZR)/64./PI/S/E
      SIGLR=P*(MGGL+MZZL+MGZL+MNNL+MGNL+MZNL)/64./PI/S/E
      EEWIWI=(FLEM*FREP*SIGLR+FREM*FLEP*SIGRL)*UNITS
      RETURN
      END
