C----------------------------------------------------------
      FUNCTION EEZIZJ(Z)
      IMPLICIT NONE
      COMMON/BSQRK/ RS,M1,M2,AE,BE,PROPZ,E4,MZ
      COMMON/EPOL/ FLEM,FREP,FREM,FLEP
      COMMON/STUFF/ UNITS,PI
      COMMON/ZIZJ/ I,J,W,SGN,AMER,AMEL
      COMMON/SESE/ ALZ,BLZ,MZI
      COMPLEX ALZ(4),BLZ(4),W(4,4)
      REAL Z,SSXLAM,EEZIZJ,MZI(4)
      REAL RS,M1,M2,AE,BE,PROPZ,E4,MZ
      REAL FLEM,FREP,FREM,FLEP,UNITS,PI
      REAL S,P,E,SIGLR,SIGRL,ESQ,E1,SGN,AMER,AMEL
      REAL ALZIS,ALZJS,BLZIS,BLZJS,WIJS
      REAL MEER,MEEL,MZZR,MZZL,MZER,MZEL
      REAL SSGT,SSGST
      INTEGER I,J
      S=RS**2
      P=SQRT(SSXLAM(S,M1**2,M2**2))/2./RS
      ESQ=SQRT(E4)
      E1=SQRT(ESQ)
      E=RS/2.
      ALZIS=ALZ(I)*CONJG(ALZ(I))
      ALZJS=ALZ(J)*CONJG(ALZ(J))
      BLZIS=BLZ(I)*CONJG(BLZ(I))
      BLZJS=BLZ(J)*CONJG(BLZ(J))
      WIJS=W(I,J)*CONJG(W(I,J))
      MEER=2*BLZIS*BLZJS*SSGT(S,AMER,Z,I,J)
      MEEL=2*ALZIS*ALZJS*SSGT(S,AMEL,Z,I,J)
      MZZR=4*ESQ*WIJS*(AE+BE)**2*
     ,(S**2-(M1**2-M2**2)**2-4*SGN*S*M1*M2+4*S*P**2*Z*Z)/PROPZ
      MZZL=4*ESQ*WIJS*(AE-BE)**2*
     ,(S**2-(M1**2-M2**2)**2-4*SGN*S*M1*M2+4*S*P**2*Z*Z)/PROPZ
      MZER=E1*SGN*(AE+BE)*(S-MZ**2)/2./PROPZ*
     ,(REAL(W(I,J)*CONJG(BLZ(I))*BLZ(J))*SSGST(S,AMER,Z,I,J)+
     ,SGN*REAL(W(I,J)*BLZ(I)*CONJG(BLZ(J)))*SSGST(S,AMER,-Z,I,J))
      MZEL=-E1*(AE-BE)*(S-MZ**2)/2./PROPZ*
     ,(REAL(W(I,J)*CONJG(ALZ(I))*ALZ(J))*SSGST(S,AMEL,Z,I,J)+
     ,SGN*REAL(W(I,J)*ALZ(I)*CONJG(ALZ(J)))*SSGST(S,AMEL,-Z,I,J))
      SIGRL=P*(MEER+MZZR+MZER)/8./PI/S/RS
      SIGLR=P*(MEEL+MZZL+MZEL)/8./PI/S/RS
C       Double count: for I=J, divide by 2
      IF (I.EQ.J) THEN
      SIGRL=SIGRL/2.
      SIGLR=SIGLR/2.
      END IF
      EEZIZJ=(FLEM*FREP*SIGLR+FREM*FLEP*SIGRL)*UNITS
      RETURN
      END
