C----------------------------------------------------------
      FUNCTION EEHA(Z)
      IMPLICIT NONE
      COMMON/BSQRK/ RS,M1,M2,AE,BE,PROPZ,E4,MZ
      COMMON/EPOL/ FLEM,FREP,FREM,FLEP
      COMMON/STUFF/ UNITS,PI
      COMMON/EEZHGS/ APBFAC
      REAL Z,SSXLAM,EEHA
      REAL RS,M1,M2,AE,BE,PROPZ,E4,MZ
      REAL FLEM,FREP,FREM,FLEP,UNITS,PI
      REAL S,P,EZ,SIGLR,SIGRL
      REAL SN2THW,CS2THW,APBFAC
      DATA SN2THW/.232/
      S=RS**2
      P=SQRT(SSXLAM(S,M1**2,M2**2))/2./RS
      CS2THW=1.-SN2THW
      SIGRL=P**3*E4*APBFAC*(AE+BE)**2*(1.-Z**2)/
     ,16./PI/RS/SN2THW/CS2THW/PROPZ
      SIGLR=P**3*E4*APBFAC*(AE-BE)**2*(1.-Z**2)/
     ,16./PI/RS/SN2THW/CS2THW/PROPZ
      EEHA=(FLEM*FREP*SIGLR+FREM*FLEP*SIGRL)*UNITS
      RETURN
      END
