import matplotlib.pyplot as plt
import numpy as np


mdm,oh20 =np.loadtxt('scalar_FIMP_x=10^0.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh21 =np.loadtxt('scalar_FIMP_x=10^1.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh22 =np.loadtxt('scalar_FIMP_x=10^2.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh23 =np.loadtxt('scalar_FIMP_x=10^3.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh24 =np.loadtxt('scalar_FIMP_x=10^4.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh25 =np.loadtxt('scalar_FIMP_x=10^5.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh26 =np.loadtxt('scalar_FIMP_x=10^6.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh27 =np.loadtxt('scalar_FIMP_x=10^7.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh28 =np.loadtxt('scalar_FIMP_x=10^8.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh29 =np.loadtxt('scalar_FIMP_x=10^9.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
mdm,oh210 =np.loadtxt('scalar_FIMP_x=10^10.dat',unpack=True,skiprows=1, usecols=range(0,2)) 
plt.figure(1)
plt.loglog(mdm,oh20,color='black',linestyle='--',alpha=0.5,label='x=1') 
plt.loglog(mdm,oh21,linestyle='--',alpha=0.5,label='x=10') 
plt.loglog(mdm,oh22,linestyle='--',alpha=0.5,label='x=10^2') 
plt.loglog(mdm,oh23,linestyle='--',alpha=0.5,label='x=10^3') 
plt.loglog(mdm,oh24,linestyle='--',alpha=0.5,label='x=10^4') 
plt.loglog(mdm,oh25,linestyle='--',alpha=0.5,label='x=10^5') 
plt.loglog(mdm,oh26,linestyle='--',alpha=0.5,label='x=10^6') 
plt.loglog(mdm,oh27,linestyle='--',alpha=0.5,label='x=10^7') 
plt.loglog(mdm,oh28,linestyle='--',alpha=0.5,label='x=10^8') 
plt.loglog(mdm,oh29,linestyle='--',alpha=0.5,label='x=10^9') 
plt.loglog(mdm,oh210,linestyle='--',alpha=0.5,label='x=10^10') 
plt.xlabel('$M_{DM}$')
plt.ylabel('$\Omega h^2$')
plt.title('Freeze-in abundance')
plt.legend()
plt.savefig('fig/scalar_fimp.pdf',format='pdf')
plt.show()

